[package]
name = "Ilesta"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Ilesta"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
clap = { version = "4.5", features = ["derive"] }