[package]
name = "Ilesta"
version = "1.0.0"
edition = "2024"
rust-version = "1.85.0"

[[bin]]
name = "Ilesta"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
clap = { version = "4.5", features = ["derive"] }